# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: gelberzwerg
email: kcrispin (ät) web (döt) de
description: > # this means to ignore newlines until "baseurl:"
  My quest until the end of August is cycling from my parent's house to the Elburs mountains in Iran. This blog shall serve as a personal notebook about the trip, and to keep whoever is interested in the progress posted.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://crispin-kirchner.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  crispin-kirchner
facebook_username: Crispy Müller
warmshowers_username: Crispin Kirchner
author: Crispin Kirchner

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - recorded-trajectory/means/bicycle/00_raw
  - recorded-trajectory/means/bicycle/01_simplified
  - recorded-trajectory/means/bicycle/02_downsampled
  - recorded-trajectory/means/bus/00_raw
  - recorded-trajectory/means/bus/01_simplified
  - recorded-trajectory/means/bus/02_downsampled
  - recorded-trajectory/means/ferry/00_raw
  - recorded-trajectory/means/ferry/01_simplified
  - recorded-trajectory/node_modules
  - recorded-trajectory/means/ferry/02_downsampled
